plugins:
  chat_integration_telegram_link_preview:
    default: "small"
    type: enum
    choices:
      - disabled
      - small
      - large
  chat_integration_telegram_link_preview_category:
    default: false
    client: false
